#spring:
#  datasouce:
#   user: root
#   passward: root
#   url: jdbc:mysql://localhost:3306/product
#   driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#   show-sql: true
#   hibernate:
#      ddl-auto: 
#   properties.hibernate.dialect: hibernate.dialect.MySQL5Dialect
         